namespace Cntryl.Portia;

/// <summary>
/// Proves the RPC path actually round-trips end to end: <see cref="FitzRemoteRequestSender" />
/// sending a request all the way through <see cref="FitzRpcRequestServer" />, the same
/// <see cref="IRequestBus" /> dispatch every other transport uses, and back — not just that each
/// side compiles against the shared contract in isolation. <see cref="InMemoryRpcClient" /> stands in
/// for the real Fitz broker, wiring a registered worker directly to a caller's <c>CallAsync</c>.
/// </summary>
public sealed class FitzRpcRoundTripTests
{
    /// <summary>
    /// Verifies that a result-bearing request sent over RPC reaches its handler and the result
    /// comes back correctly deserialized.
    /// </summary>
    [Fact]
    public async Task ShouldRoundTripResultBearingRequestOverRpc()
    {
        var rpc = new InMemoryRpcClient();
        var serializer = TestJson.Serializer(typeof(RpcGetValue));
        using var busHost = TestRequestBus.Create();
        var server = new FitzRpcRequestServer(rpc, busHost.ScopeFactory);
        _ = await server.RegisterAsync<RpcGetValue, int>();
        var sender = new FitzRemoteRequestSender(rpc, serializer, serializer);

        var result = await sender.SendAsync<RpcGetValue, int>(new RpcGetValue(), new RequestRouteValues(), actorToken: null);

        Assert.True(result.IsSuccess);
        Assert.Equal(7, result.Value);
    }

    /// <summary>
    /// Verifies that a no-result request sent over RPC reaches its handler.
    /// </summary>
    [Fact]
    public async Task ShouldRoundTripNoResultRequestOverRpc()
    {
        var rpc = new InMemoryRpcClient();
        var serializer = TestJson.Serializer(typeof(RpcChangeValue));
        var handler = new RpcChangeValueHandler();
        using var busHost = TestRequestBus.Create(rpcChangeValueHandler: handler);
        var server = new FitzRpcRequestServer(rpc, busHost.ScopeFactory);
        _ = await server.RegisterAsync<RpcChangeValue>();
        var sender = new FitzRemoteRequestSender(rpc, serializer, serializer);

        var result = await sender.SendAsync(new RpcChangeValue(99), new RequestRouteValues(), actorToken: null);

        Assert.True(result.IsSuccess);
        Assert.Equal(99, handler.LastValue);
    }

    /// <summary>
    /// Verifies that a request whose carried actor token fails re-validation on the receiving
    /// side never reaches its handler — the same "always honor expiration" guarantee the queue
    /// path has, enforced here at the point the RPC call is actually received, not just sent.
    /// </summary>
    [Fact]
    public async Task ShouldRejectRequestWhenActorTokenFailsRevalidationOnReceipt()
    {
        var rpc = new InMemoryRpcClient();
        var serializer = TestJson.Serializer(typeof(RpcChangeValue));
        var handler = new RpcChangeValueHandler();
        using var busHost = TestRequestBus.Create(rpcChangeValueHandler: handler, actorValidator: new RejectingActorValidator());
        var server = new FitzRpcRequestServer(rpc, busHost.ScopeFactory);
        _ = await server.RegisterAsync<RpcChangeValue>();
        var sender = new FitzRemoteRequestSender(rpc, serializer, serializer);

        var result = await sender.SendAsync(new RpcChangeValue(1), new RequestRouteValues(), actorToken: "any-token");

        Assert.False(result.IsSuccess);
        Assert.Equal(RequestErrorKind.Unauthorized, result.Error!.Kind);
        Assert.Equal("Token expired.", result.Error.Message);
        Assert.Null(handler.LastValue);
    }

    /// <summary>
    /// Verifies that <c>RegisterRequestsAsync</c> — generated by
    /// <c>PortiaServiceRegistrationGenerator</c> — registers a worker for every routed,
    /// <see cref="ICallable" /> request in the compilation without a single manual
    /// <see cref="FitzRpcRequestServer.RegisterAsync{TRequest}" /> call, the same way
    /// Explicit component declarations cover DI registration.
    /// </summary>
    [Fact]
    public async Task ShouldDispatchRequestRegisteredEntirelyByGeneratedRpcWorkerRegistration()
    {
        var rpc = new InMemoryRpcClient();
        var serializer = TestJson.Serializer(typeof(RpcGetValue));
        using var busHost = TestRequestBus.Create();
        var server = new FitzRpcRequestServer(rpc, busHost.ScopeFactory);

        // No server.RegisterAsync<RpcGetValue, int>() call anywhere — this alone must cover it.
        await using var registration = await server.RegisterRequestsAsync();

        var sender = new FitzRemoteRequestSender(rpc, serializer, serializer);
        var result = await sender.SendAsync<RpcGetValue, int>(new RpcGetValue(), new RequestRouteValues(), actorToken: null);

        Assert.True(result.IsSuccess);
        Assert.Equal(7, result.Value);
    }

    sealed class AlwaysValidActorValidator : IRequestActorValidator
    {
        public ValueTask<Result<System.Security.Claims.ClaimsPrincipal>> ValidateAsync(string? token, CancellationToken ct = default) =>
            ValueTask.FromResult(Result<System.Security.Claims.ClaimsPrincipal>.Success(RequestActor.System));
    }

    sealed class RejectingActorValidator : IRequestActorValidator
    {
        public ValueTask<Result<System.Security.Claims.ClaimsPrincipal>> ValidateAsync(string? token, CancellationToken ct = default) =>
            ValueTask.FromResult(Result<System.Security.Claims.ClaimsPrincipal>.Failure(
                new RequestError(RequestErrorKind.Unauthorized, "Token expired.")));
    }
}

[RequestRoute(realm: "test", area: "rpc", resource: "value", operation: "get")]
[Discriminator("test.rpc.get-value")]
sealed record RpcGetValue : IRequest<int>, ICallable;

sealed class RpcGetValueHandler : IRequestHandler<RpcGetValue, int>
{
    public ValueTask<Result<int>> HandleAsync(IRequestContext<RpcGetValue> context, CancellationToken ct) =>
        ValueTask.FromResult(Result<int>.Success(7));
}

[RequestRoute(realm: "test", area: "rpc", resource: "value", operation: "change")]
[Discriminator("test.rpc.change-value")]
sealed record RpcChangeValue(int Value) : IRequest, ICallable;

sealed class RpcChangeValueHandler : IRequestHandler<RpcChangeValue>
{
    public int? LastValue { get; private set; }

    public ValueTask<Result> HandleAsync(IRequestContext<RpcChangeValue> context, CancellationToken ct)
    {
        LastValue = context.Request.Value;
        return ValueTask.FromResult(Result.Success);
    }
}
