using System.Text.Json;
using System.Text.Json.Serialization;

namespace Cntryl.Portia;

[PortiaJsonContext]
[JsonSourceGenerationOptions(JsonSerializerDefaults.Web, PropertyNamingPolicy = JsonKnownNamingPolicy.SnakeCaseLower)]
[JsonSerializable(typeof(UniversalAction))]
[JsonSerializable(typeof(GadgetRenamed))]
[JsonSerializable(typeof(OrderPlacedV1))]
[JsonSerializable(typeof(OrderPlacedV2))]
[JsonSerializable(typeof(WidgetNamed))]
[JsonSerializable(typeof(WidgetRenamed))]
[JsonSerializable(typeof(NoWorkerRegisteredPing))]
[JsonSerializable(typeof(RpcChangeValue))]
[JsonSerializable(typeof(RpcGetValue))]
[JsonSerializable(typeof(HttpCreateOrder))]
[JsonSerializable(typeof(HttpCreatePayment))]
[JsonSerializable(typeof(HttpMoney))]
[JsonSerializable(typeof(HttpOrderLine))]
[JsonSerializable(typeof(List<HttpOrderLine>))]
[JsonSerializable(typeof(HttpGetWidget))]
[JsonSerializable(typeof(HttpGuardedAction))]
[JsonSerializable(typeof(HttpListWidgets))]
[JsonSerializable(typeof(HttpSendPing))]
[JsonSerializable(typeof(HttpOptionalBody))]
[JsonSerializable(typeof(SerializerTestRequest))]
[JsonSerializable(typeof(SerializerTestUuidRequest))]
[JsonSerializable(typeof(RequestEnvelopeContextTests.EnvelopeCommand))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.MixedShape))]
[JsonSerializable(typeof(ConformanceEvent))]
[JsonSerializable(typeof(TenantDeregistered))]
[JsonSerializable(typeof(TenantRegistered))]
[JsonSerializable(typeof(FitzHostedRequest))]
[JsonSerializable(typeof(FitzOutboundCallableRequest))]
[JsonSerializable(typeof(FitzOutboundOnlyRequest))]
[JsonSerializable(typeof(TelemetryFailureAction))]
[JsonSerializable(typeof(TelemetryGuardedAction))]
[JsonSerializable(typeof(TelemetrySequence))]
[JsonSerializable(typeof(TelemetryGuardedSequence))]
[JsonSerializable(typeof(TelemetrySuccessAction))]
[JsonSerializable(typeof(AuthorizedAction))]
[JsonSerializable(typeof(GetOrder))]
[JsonSerializable(typeof(GuardedAction))]
[JsonSerializable(typeof(GuardedAndAuthorizedAction))]
[JsonSerializable(typeof(GuardedQuery))]
[JsonSerializable(typeof(GuardedSequence))]
[JsonSerializable(typeof(TieredRequest))]
[JsonSerializable(typeof(ClockProbe))]
[JsonSerializable(typeof(ChangeValue))]
[JsonSerializable(typeof(GetValue))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.PipelineAction))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.PipelineQuery))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.PipelineStream))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.InvalidPipelineAction))]
[JsonSerializable(typeof(RequestPipelineBehaviorTests.NestedConcurrentAction))]
[JsonSerializable(typeof(CreateUser))]
[JsonSerializable(typeof(SendWelcomeEmail))]
[JsonSerializable(typeof(UnhandledEvent))]
[JsonSerializable(typeof(HierarchyChildEvent))]
[JsonSerializable(typeof(QueueRunnerTests.InvalidChangeValue))]
[JsonSerializable(typeof(RunnerFaultVisibilityTests.RunnerFaultAction))]
[JsonSerializable(typeof(TransportExecutionContextTests.TransportCommand))]
[JsonSerializable(typeof(ValueAudited))]
[JsonSerializable(typeof(ValueChanged))]
[JsonSerializable(typeof(ValueIncremented))]
[JsonSerializable(typeof(string))]
[JsonSerializable(typeof(int))]
[JsonSerializable(typeof(Uuid))]
sealed partial class PortiaTestJsonContext : JsonSerializerContext;
