<Project>
  <Import Project="../Directory.Build.props"/>

  <PropertyGroup>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Cntryl.Portia.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit"/>
  </ItemGroup>
</Project>
