using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>
/// Registers an RPC worker for every routed, <c>ICallable</c> request declared in a compilation —
/// split out from <see cref="PortiaServiceRegistrationGenerator" /> as its own generator since
/// this is a genuinely independent concern (registering Fitz RPC workers) with its own reason to
/// change, only relevant to a project that references Portia.Fitz at all, not entangled with DI
/// registration for reactors, projectors, or request handlers.
/// </summary>
[Generator(LanguageNames.CSharp)]
public sealed class FitzRpcWorkerRegistrationGenerator : IIncrementalGenerator
{
    const string FitzRpcRequestServerMetadataName = "Cntryl.Portia.FitzRpcRequestServer";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => RequestTransportDiscovery.IsCandidate(node),
                static (syntaxContext, _) => RequestTransportDiscovery.GetRequestTransportComponent(syntaxContext))
            .Where(static request => request is not null)
            .Select(static (request, _) => request!)
            .Collect();

        context.RegisterSourceOutput(
            requests.Combine(context.CompilationProvider),
            static (sourceContext, pair) => Generate(sourceContext, pair.Left, pair.Right));
    }

    static void Generate(SourceProductionContext context, ImmutableArray<RequestTransportComponent> requests, Compilation compilation)
    {
        if (requests.IsDefaultOrEmpty)
            return;

        // Only relevant when the consuming project actually references Portia.Fitz
        // (FitzRpcRequestServer) — most projects (a pure HTTP API, say) have no interest in it,
        // so this is skipped silently rather than failing every build that doesn't reference
        // Fitz at all.
        if (compilation.GetTypeByMetadataName(FitzRpcRequestServerMetadataName) is null)
            return;

        var callableRequests = requests
            .Where(request => request.Transports.HasFlag(RequestTransports.Callable))
            .GroupBy(request => request.TypeName, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(request => request.TypeName, StringComparer.Ordinal)
            .ToArray();

        if (callableRequests.Length == 0)
            return;

        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("namespace Cntryl.Portia;")
            .AppendLine()
            .AppendLine("/// <summary>")
            .AppendLine("/// Registers an RPC worker for every routed, ICallable request declared in this")
            .AppendLine("/// compilation, so a host never has to remember to register one by hand per request type.")
            .AppendLine("/// </summary>")
            .AppendLine("public static class PortiaGeneratedFitzRpcServerExtensions")
            .AppendLine("{")
            .AppendLine("    /// <summary>")
            .AppendLine("    /// Registers every routed, ICallable request declared in this compilation as an RPC")
            .AppendLine("    /// worker.")
            .AppendLine("    /// </summary>")
            .AppendLine("    /// <param name=\"server\">The RPC server to register workers on.</param>")
            .AppendLine("    /// <param name=\"ct\">A token that can cancel the operation.</param>")
            .AppendLine("    /// <returns>A task representing every registration.</returns>")
            .AppendLine("    public static async global::System.Threading.Tasks.ValueTask RegisterPortiaGeneratedRpcWorkersAsync(")
            .AppendLine("        this global::Cntryl.Portia.FitzRpcRequestServer server,")
            .AppendLine("        global::System.Threading.CancellationToken ct = default)")
            .AppendLine("    {");

        foreach (var request in callableRequests)
        {
            _ = source
                .Append("        _ = await server.RegisterAsync<")
                .Append(request.TypeName)
                .Append(request.ResultType is null ? string.Empty : $", {request.ResultType}")
                .AppendLine(">(ct).ConfigureAwait(false);");
        }

        _ = source
            .AppendLine("    }")
            .AppendLine("}");

        context.AddSource("PortiaGeneratedFitzRpcServerExtensions.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
