using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>Advertises Portia JSON roots to referencing compilations.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class JsonRootMarkerGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var roots = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is TypeDeclarationSyntax,
                static (syntax, _) => Roots(syntax))
            .Where(static roots => roots is not null)
            .SelectMany(static (roots, _) => roots!)
            .Collect();
        context.RegisterSourceOutput(roots, static (output, models) => Generate(output, models));
    }

    static IEnumerable<RootModel>? Roots(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.GetDeclaredSymbol((TypeDeclarationSyntax)context.Node) is not INamedTypeSymbol type
            || !type.GetAttributes().Any(attribute =>
                attribute.AttributeClass?.ToDisplayString() == "Cntryl.Portia.PortiaJsonContextAttribute"))
        {
            return null;
        }

        return type.GetAttributes().Where(attribute =>
                attribute.AttributeClass?.ToDisplayString() ==
                "System.Text.Json.Serialization.JsonSerializableAttribute")
            .Select(attribute => attribute.ConstructorArguments.FirstOrDefault().Value)
            .OfType<ITypeSymbol>()
            .Select(root => new RootModel(
                root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat),
                type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), FactoryName(type)));
    }

    static void Generate(SourceProductionContext context, IReadOnlyCollection<RootModel> roots)
    {
        if (roots.Count == 0)
            return;
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n#pragma warning disable CS1591\n");
        foreach (var root in roots.Distinct().OrderBy(model => model.RootType, StringComparer.Ordinal))
        {
            _ = source.Append("[assembly: global::Cntryl.Portia.PortiaJsonRootAttribute(typeof(")
                .Append(root.RootType).Append("), typeof(").Append(root.ContextType).Append("), typeof(global::Cntryl.Portia.Generated.")
                .Append(root.FactoryName).AppendLine("))]");
        }
        foreach (var contextGroup in roots.Distinct().GroupBy(model => model.ContextType, StringComparer.Ordinal))
        {
            var first = contextGroup.First();
            _ = source.Append("namespace Cntryl.Portia.Generated { [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)] public static class ")
                .Append(first.FactoryName)
                .Append(" { public static global::System.Text.Json.Serialization.JsonSerializerContext Create(global::System.Text.Json.JsonSerializerOptions options) => new ")
                .Append(first.ContextType).AppendLine("(options); } }");
        }

        context.AddSource("PortiaJsonRoots.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    static string FactoryName(INamedTypeSymbol context) => "PortiaJsonContextFactory_" +
        string.Concat((context.ContainingAssembly.Name + "_" + context.ToDisplayString())
            .Select(character => char.IsLetterOrDigit(character) ? character : '_'));

    sealed record RootModel(string RootType, string ContextType, string FactoryName);
}
