using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>Generates typed transport descriptors for explicitly selected request contracts.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class PortiaServiceRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => RequestTransportDiscovery.IsCandidate(node),
                static (syntaxContext, _) => RequestTransportDiscovery.GetRequestTransportComponent(syntaxContext))
            .Where(static request => request is not null)
            .Select(static (request, _) => request!)
            .Collect();
        var components = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => node is Microsoft.CodeAnalysis.CSharp.Syntax.ClassDeclarationSyntax,
                static (syntaxContext, _) => RegistrationComponentDiscovery.GetHandlerOrAuthorizerTypeName(syntaxContext))
            .Where(static component => component is not null)
            .Select(static (component, _) => component!)
            .Collect();
        context.RegisterSourceOutput(requests.Combine(components).Combine(context.CompilationProvider),
            static (sourceContext, pair) => Generate(sourceContext, pair.Left.Left, pair.Left.Right, pair.Right));
    }

    static void Generate(
        SourceProductionContext context,
        ImmutableArray<RequestTransportComponent> requests,
        ImmutableArray<string> components,
        Compilation compilation)
    {
        if (requests.IsDefaultOrEmpty || compilation.GetTypeByMetadataName("Cntryl.Portia.PortiaBuilder") is null)
            return;

        var ordered = requests
            .GroupBy(request => request.TypeName, StringComparer.Ordinal)
            .Select(group => group.First())
            .OrderBy(request => request.TypeName, StringComparer.Ordinal)
            .ToArray();
        var names = GeneratedRegistrationNames.Resolve(ordered.Select(request => request.TypeName).Concat(components));

        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("namespace Cntryl.Portia;")
            .AppendLine("internal static partial class PortiaGeneratedRegistrations")
            .AppendLine("{");

        foreach (var request in ordered)
        {
            _ = source.Append("    /// <summary>Registers the transports <see cref=\"")
                .Append(request.TypeName.StartsWith("global::", StringComparison.Ordinal) ? request.TypeName.Substring(8) : request.TypeName)
                .AppendLine("\" /> declares.</summary>")
                .Append("    public static global::Cntryl.Portia.PortiaBuilder ").Append(names[request.TypeName])
                .AppendLine("(this global::Cntryl.Portia.PortiaBuilder builder)")
                .AppendLine("    {")
                .AppendLine("        global::System.ArgumentNullException.ThrowIfNull(builder);")
                .Append("        return builder.AddGeneratedRequest(");
            RequestTransportRegistrationEmitter.AppendConstruction(source, request);
            _ = source.AppendLine(");").AppendLine("    }");
        }

        _ = source.AppendLine("}");
        context.AddSource("PortiaGeneratedServiceCollectionExtensions.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }
}
