using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>Generates typed transport descriptors for explicitly selected request contracts.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class PortiaServiceRegistrationGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var requests = context.SyntaxProvider
            .CreateSyntaxProvider(
                static (node, _) => RequestTransportDiscovery.IsCandidate(node),
                static (syntaxContext, _) => RequestTransportDiscovery.GetRequestTransportComponent(syntaxContext))
            .Where(static request => request is not null)
            .Select(static (request, _) => request!)
            .Collect();
        context.RegisterSourceOutput(requests.Combine(context.CompilationProvider),
            static (sourceContext, pair) => Generate(sourceContext, pair.Left, pair.Right));
    }

    static void Generate(SourceProductionContext context, ImmutableArray<RequestTransportComponent> requests, Compilation compilation)
    {
        if (requests.IsDefaultOrEmpty || compilation.GetTypeByMetadataName("Microsoft.Extensions.DependencyInjection.IServiceCollection") is null)
            return;
        var source = new StringBuilder()
            .AppendLine("// <auto-generated />")
            .AppendLine("#nullable enable")
            .AppendLine("namespace Cntryl.Portia;")
            .AppendLine("internal static class PortiaGeneratedServiceCollectionExtensions")
            .AppendLine("{")
            .AppendLine("    public static void RegisterRequest(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services, global::System.Type requestType)")
            .AppendLine("    {");
        RequestTransportsRegistration.AppendRegistrations(source, requests);
        _ = source.AppendLine("    }").AppendLine("}");
        context.AddSource("PortiaGeneratedServiceCollectionExtensions.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    static class RequestTransportsRegistration
    {
        public static void AppendRegistrations(StringBuilder source, ImmutableArray<RequestTransportComponent> requests)
        {
            var ordered = requests
                .GroupBy(request => request.TypeName, StringComparer.Ordinal)
                .Select(group => group.First())
                .OrderBy(request => request.TypeName, StringComparer.Ordinal)
                .ToArray();

            foreach (var request in ordered)
            {
                _ = source.Append("        if (requestType == typeof(").Append(request.TypeName).AppendLine("))")
                    .Append("        _ = global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddSingleton(services, new global::Cntryl.Portia.RequestTransportRegistration(")
                    .Append("typeof(")
                    .Append(request.TypeName)
                    .Append("), ")
                    .Append(RequestTransportDiscovery.FormatTransports(request.Transports))
                    .Append(", new global::Cntryl.Portia.RequestRouteAttribute(")
                    .Append(RequestTransportDiscovery.FormatStringLiteral(request.Realm))
                    .Append(", ")
                    .Append(RequestTransportDiscovery.FormatStringLiteral(request.Area))
                    .Append(", ")
                    .Append(RequestTransportDiscovery.FormatStringLiteral(request.Resource))
                    .Append(", ")
                    .Append(RequestTransportDiscovery.FormatStringLiteral(request.Operation))
                    .Append(')');
                if (request.Transports.HasFlag(RequestTransports.Callable))
                {
                    _ = source.Append(", static (registrar, ct) => registrar.RegisterAsync<")
                        .Append(request.TypeName)
                        .Append(request.ResultType is null ? string.Empty : $", {request.ResultType}")
                        .Append(">(ct)");
                }
                _ = source.AppendLine("));");
            }
        }
    }
}
