<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Description>Roslyn source generators for Portia.</Description>
    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Http/RequestHttpBindingGenerator.cs"/>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="buildTransitive/Portia.Generators.props" Pack="true" PackagePath="buildTransitive/Cntryl.Portia.Generators.props"/>
    <None Include="$(OutputPath)$(AssemblyName).dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="../../docs/AnalyzerReleases.Shipped.md"/>
    <AdditionalFiles Include="../../docs/AnalyzerReleases.Unshipped.md"/>
  </ItemGroup>
</Project>
