using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Cntryl.Portia;

/// <summary>Generates explicitly named module entry points and their compile-time imports.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class PortiaModuleGenerator : IIncrementalGenerator
{
    static readonly DiagnosticDescriptor UnsupportedModule = new(
        "PORTIA014", "Unsupported module declaration",
        "Module '{0}' must be a non-generic, top-level partial class with internal or public accessibility",
        "Portia", DiagnosticSeverity.Error, isEnabledByDefault: true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var modules = context.SyntaxProvider.ForAttributeWithMetadataName("Cntryl.Portia.PortiaModuleAttribute",
            static (node, _) => node is ClassDeclarationSyntax,
            static (syntaxContext, _) => (INamedTypeSymbol)syntaxContext.TargetSymbol);
        context.RegisterSourceOutput(modules.Combine(context.CompilationProvider), static (output, input) => Generate(output, input.Left, input.Right));
    }

    static void Generate(SourceProductionContext context, INamedTypeSymbol module, Compilation compilation)
    {
        if (module.IsGenericType || module.ContainingType is not null
            || module.DeclaredAccessibility is not (Accessibility.Public or Accessibility.Internal)
            || module.DeclaringSyntaxReferences.Any(reference => reference.GetSyntax() is not ClassDeclarationSyntax declaration
                || !declaration.Modifiers.Any(SyntaxKind.PartialKeyword)))
        {
            context.ReportDiagnostic(Diagnostic.Create(UnsupportedModule, module.Locations.FirstOrDefault(), module.Name));
            return;
        }
        var types = SourceTypes(compilation.Assembly.GlobalNamespace).ToArray();
        var source = new StringBuilder().AppendLine("// <auto-generated />").AppendLine("#nullable enable");
        if (!module.ContainingNamespace.IsGlobalNamespace)
            _ = source.Append("namespace ").Append(module.ContainingNamespace.ToDisplayString()).AppendLine(";");
        _ = source.Append("partial class @").Append(module.Name).AppendLine(" : global::Cntryl.Portia.IPortiaModule")
            .AppendLine("{")
            .AppendLine("    /// <summary>Registers the components and explicit imports discovered for this module.</summary>")
            .AppendLine("    public static void Register(global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)")
            .AppendLine("    {");
        var attribute = module.GetAttributes().Single(value => value.AttributeClass?.ToDisplayString() == "Cntryl.Portia.PortiaModuleAttribute");
        foreach (var import in attribute.ConstructorArguments[0].Values)
        {
            if (import.Value is INamedTypeSymbol importedModule)
            {
                _ = source.Append("        _ = global::Cntryl.Portia.PortiaModuleServiceCollectionExtensions.AddPortiaModule<")
                    .Append(importedModule.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine(">(services);");
            }
        }
        var hasComponents = types.Any(type => !type.IsAbstract && (type.AllInterfaces.Any(iface =>
            iface.ContainingNamespace.ToDisplayString() == "Cntryl.Portia"
            && (iface.Name == "IRequestHandler" || iface.Name == "IStreamRequestHandler" || iface.Name == "IRequestAuthorizer"))
            || Inherits(type, "Reactor") || Inherits(type, "Projector")
            || type.GetAttributes().Any(value => value.AttributeClass?.ToDisplayString() == "Cntryl.Portia.RequestRouteAttribute")));
        if (hasComponents)
            _ = source.AppendLine("        _ = global::Cntryl.Portia.PortiaGeneratedServiceCollectionExtensions.AddPortiaGeneratedComponents(services);");
        foreach (var type in types.Where(type => !type.IsAbstract && Inherits(type, "DomainEvent") && Accessible(type)))
        {
            _ = source.Append("        global::Cntryl.Portia.PortiaModuleServiceCollectionExtensions.AddPortiaEvent<")
                .Append(type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)).AppendLine(">(services);");
        }
        if (compilation.GetTypeByMetadataName("Cntryl.Portia.JsonDomainEventSerializer") is not null)
        {
            _ = source.AppendLine("        global::Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddSingleton<global::Cntryl.Portia.IDomainEventSerializer, global::Cntryl.Portia.JsonDomainEventSerializer>(services);");
        }
        _ = source.AppendLine("    }").AppendLine("}");
        context.AddSource(GeneratedTypeShape.HintName(module) + ".Module.g.cs", source.ToString());
    }

    static IEnumerable<INamedTypeSymbol> SourceTypes(INamespaceOrTypeSymbol parent)
    {
        foreach (var member in parent.GetMembers())
        {
            if (member is INamedTypeSymbol type)
                yield return type;
            if (member is INamespaceOrTypeSymbol child)
            {
                foreach (var nested in SourceTypes(child))
                    yield return nested;
            }
        }
    }

    static bool Inherits(INamedTypeSymbol type, string name)
    {
        for (var current = type.BaseType; current is not null; current = current.BaseType)
        {
            if (current.Name == name && current.ContainingNamespace.ToDisplayString() == "Cntryl.Portia")
                return true;
        }
        return false;
    }

    static bool Accessible(INamedTypeSymbol type)
    {
        for (var current = type; current is not null; current = current.ContainingType)
        {
            if (current.IsGenericType || current.DeclaredAccessibility is Accessibility.Private or Accessibility.Protected or Accessibility.ProtectedAndInternal)
                return false;
        }
        return true;
    }
}
