using System.Collections.Immutable;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>Intercepts ASP.NET Core application construction to install Portia OpenAPI automatically.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class WebApplicationOpenApiGenerator : IIncrementalGenerator
{
    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var calls = context.SyntaxProvider.CreateSyntaxProvider(
                static (node, _) => node is InvocationExpressionSyntax
                {
                    Expression: MemberAccessExpressionSyntax { Name.Identifier.ValueText: "Build" or "Create" }
                },
                static (syntaxContext, _) => Analyze(syntaxContext))
            .Where(static call => call is not null)
            .Select(static (call, _) => call!)
            .Collect();
        context.RegisterSourceOutput(calls, static (sourceContext, models) => Generate(sourceContext, models));
    }

    static Call? Analyze(GeneratorSyntaxContext context)
    {
        if (context.SemanticModel.Compilation.GetTypeByMetadataName("Cntryl.Portia.PortiaOpenApi") is null
            || context.SemanticModel.GetSymbolInfo(context.Node).Symbol is not IMethodSymbol method)
        {
            return null;
        }

        var location = context.SemanticModel.GetInterceptableLocation((InvocationExpressionSyntax)context.Node);
        return location is null
            ? null
            : method.Name switch
            {
                "Build" when method.ContainingType.ToDisplayString() ==
                             "Microsoft.AspNetCore.Builder.WebApplicationBuilder"
                             && method.Parameters.Length == 0 => new Call(CallKind.Build, location),
                "Create" when method.ContainingType.ToDisplayString() == "Microsoft.AspNetCore.Builder.WebApplication"
                              && method.Parameters.Length == 1 && method.Parameters[0].Type is IArrayTypeSymbol
                              {
                                  ElementType.SpecialType: SpecialType.System_String
                              }
                    => new Call(CallKind.Create, location),
                _ => null
            };
    }

    static void Generate(SourceProductionContext context, ImmutableArray<Call> calls)
    {
        if (calls.IsDefaultOrEmpty)
        {
            return;
        }

        var source = new StringBuilder("""
                                       // <auto-generated />
                                       #nullable enable
                                       namespace System.Runtime.CompilerServices
                                       {
                                           [global::System.AttributeUsage(global::System.AttributeTargets.Method, AllowMultiple = true)]
                                           file sealed class InterceptsLocationAttribute : global::System.Attribute
                                           {
                                               public InterceptsLocationAttribute(int version, string data) { _ = version; _ = data; }
                                           }
                                       }
                                       namespace Cntryl.Portia.Generated
                                       {
                                       file static class PortiaWebApplicationInterceptors
                                       {
                                       """);
        for (var i = 0; i < calls.Length; i++)
        {
            var call = calls[i];
            _ = source.Append("    [global::System.Runtime.CompilerServices.InterceptsLocation(")
                .Append(call.Location.Version)
                .Append(", \"").Append(call.Location.Data).AppendLine("\")]");
            _ = call.Kind == CallKind.Build
                ? source.Append("    public static global::Microsoft.AspNetCore.Builder.WebApplication Call").Append(i)
                    .AppendLine(
                        "(this global::Microsoft.AspNetCore.Builder.WebApplicationBuilder builder) => global::Cntryl.Portia.PortiaOpenApi.Build(builder);")
                : source.Append("    public static global::Microsoft.AspNetCore.Builder.WebApplication Call").Append(i)
                    .AppendLine("(string[]? args = null) => global::Cntryl.Portia.PortiaOpenApi.Create(args);");
        }

        _ = source.AppendLine("}").AppendLine("}");
        context.AddSource("PortiaGeneratedWebApplication.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    enum CallKind
    {
        Build,
        Create
    }

    sealed class Call(CallKind kind, InterceptableLocation location)
    {
        public CallKind Kind { get; } = kind;
        public InterceptableLocation Location { get; } = location;
    }
}
