<Project>
  <Target Name="ValidatePackageMetadata" BeforeTargets="Pack" Condition="'$(IsPackable)' == 'true'">
    <Error Condition="'$(PackageId)' == ''" Text="Packable projects must define PackageId." />
    <Error Condition="'$(Description)' == ''" Text="Packable projects must define Description." />
    <Error Condition="'$(Authors)' == ''" Text="Packable projects must define Authors." />
    <Error Condition="'$(RepositoryUrl)' == ''" Text="Packable projects must define RepositoryUrl." />
  </Target>
</Project>
