<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Minimal API wiring for Portia requests.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi"/>
    <PackageReference Include="Microsoft.OpenApi"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Portia.Abstractions/Portia.Abstractions.csproj"/>
    <ProjectReference Include="../Portia.DependencyInjection/Portia.DependencyInjection.csproj"/>
  </ItemGroup>
</Project>
