<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Minimal API wiring for Portia requests.</Description>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../Portia.Abstractions/Portia.Abstractions.csproj" />
  </ItemGroup>
</Project>
