<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>Cntryl.Portia.Consumer</RootNamespace>
    <NoWarn>$(NoWarn);CS1591</NoWarn>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Cntryl.Portia.Generated</InterceptorsNamespaces>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Cntryl.Fitz" />
    <PackageReference Include="Microsoft.AspNetCore.TestHost" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
    <ProjectReference Include="../Consumer.Contracts/Consumer.Contracts.csproj" />
    <ProjectReference Include="../Consumer.FeatureOne/Consumer.FeatureOne.csproj" />
    <ProjectReference Include="../Consumer.FeatureTwo/Consumer.FeatureTwo.csproj" />
    <ProjectReference Include="../../src/Portia.Testing/Portia.Testing.csproj" />
    <ProjectReference Include="../../src/Portia.AspNetCore/Portia.AspNetCore.csproj" />
    <ProjectReference Include="../../src/Portia.Fitz/Portia.Fitz.csproj" />
    <ProjectReference Include="../../src/Portia.Generators/Portia.Generators.csproj" />
  </ItemGroup>
</Project>
