using System.Globalization;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Cntryl.Portia;

/// <summary>Advertises Portia JSON roots to referencing compilations.</summary>
[Generator(LanguageNames.CSharp)]
public sealed class JsonRootMarkerGenerator : IIncrementalGenerator
{
    static readonly DiagnosticDescriptor UnsupportedContext = new("PORTIA030", "Unsupported Portia JSON context",
        "JSON context '{0}' cannot be generated: {1}", "Portia", DiagnosticSeverity.Error, true);

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var contexts = context.SyntaxProvider.ForAttributeWithMetadataName("Cntryl.Portia.PortiaJsonContextAttribute",
            static (node, _) => node is TypeDeclarationSyntax,
            static (syntax, _) => Model((INamedTypeSymbol)syntax.TargetSymbol)).Collect();
        context.RegisterSourceOutput(contexts, static (output, models) =>
        {
            foreach (var model in models)
                if (model.Reason is { } reason)
                    output.ReportDiagnostic(Diagnostic.Create(UnsupportedContext, model.Location.ToLocation(), model.Name, reason));
            Generate(output, models.SelectMany(model => model.Roots).ToArray());
        });
    }

    static ContextModel Model(INamedTypeSymbol type)
    {
        var name = type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var location = DiagnosticLocation.From(type.Locations.FirstOrDefault() ?? Location.None);
        if (JsonContextShape.UnsupportedReason(type) is { } reason)
            return new ContextModel(name, location, reason, []);
        var factory = FactoryName(type);
        var roots = type.GetAttributes().Where(attribute =>
                attribute.AttributeClass?.ToDisplayString() == "System.Text.Json.Serialization.JsonSerializableAttribute")
            .Select(attribute => attribute.ConstructorArguments.FirstOrDefault().Value)
            .OfType<ITypeSymbol>()
            .Select(root => new RootModel(root.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat), name, factory))
            .ToArray();
        return new ContextModel(name, location, null, roots);
    }

    static void Generate(SourceProductionContext context, IReadOnlyCollection<RootModel> roots)
    {
        if (roots.Count == 0)
            return;
        var source = new StringBuilder("// <auto-generated />\n#nullable enable\n#pragma warning disable CS1591\n");
        foreach (var root in roots.Distinct().OrderBy(model => model.RootType, StringComparer.Ordinal)
                     .ThenBy(model => model.ContextType, StringComparer.Ordinal))
        {
            _ = source.Append("[assembly: global::Cntryl.Portia.PortiaJsonRootAttribute(typeof(")
                .Append(root.RootType).Append("), typeof(").Append(root.ContextType)
                .Append("), typeof(global::Cntryl.Portia.Generated.")
                .Append(root.FactoryName).AppendLine("))]");
        }

        foreach (var contextGroup in roots.Distinct().GroupBy(model => model.ContextType, StringComparer.Ordinal)
                     .OrderBy(group => group.Key, StringComparer.Ordinal))
        {
            var first = contextGroup.First();
            _ = source.Append(
                    "namespace Cntryl.Portia.Generated { [global::System.ComponentModel.EditorBrowsable(global::System.ComponentModel.EditorBrowsableState.Never)] public static class ")
                .Append(first.FactoryName)
                .Append(
                    " { public static global::System.Text.Json.Serialization.JsonSerializerContext Create(global::System.Text.Json.JsonSerializerOptions options) => new ")
                .Append(first.ContextType).AppendLine("(options); } }");
        }

        context.AddSource("PortiaJsonRoots.g.cs", SourceText.From(source.ToString(), Encoding.UTF8));
    }

    // Length-delimited assembly identity and full context name, encoded as UTF-16 hex: injective,
    // deterministic and valid as a C# identifier, even for escaped/Unicode identifiers.
    static string FactoryName(INamedTypeSymbol context)
    {
        var assembly = context.ContainingAssembly.Identity.ToString();
        var type = context.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);
        var identity = assembly.Length.ToString(CultureInfo.InvariantCulture) + ":" + assembly + type;
        return "PortiaJsonContextFactory_" + string.Concat(identity.Select(character =>
            ((int)character).ToString("X4", CultureInfo.InvariantCulture)));
    }

    sealed record ContextModel(string Name, DiagnosticLocation Location, string? Reason, RootModel[] Roots);

    sealed record RootModel(string RootType, string ContextType, string FactoryName);
}
