<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <InterceptorsNamespaces>$(InterceptorsNamespaces);Cntryl.Portia.Generated</InterceptorsNamespaces>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="BenchmarkDotNet"/>
    <PackageReference Include="Microsoft.AspNetCore.TestHost"/>
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol"/>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Portia.Abstractions/Portia.Abstractions.csproj"/>
    <ProjectReference Include="../../src/Portia.DependencyInjection/Portia.DependencyInjection.csproj"/>
    <ProjectReference Include="../../src/Portia.AspNetCore/Portia.AspNetCore.csproj"/>
    <ProjectReference Include="../../src/Portia.Testing/Portia.Testing.csproj"/>
    <ProjectReference Include="../../src/Portia.Fitz/Portia.Fitz.csproj"/>
    <ProjectReference Include="../../src/Portia.Telemetry/Portia.Telemetry.csproj"/>
    <ProjectReference Include="../../src/Portia.Generators/Portia.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
    <ProjectReference Include="../../src/Portia.AspNetCore.Generators/Portia.AspNetCore.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"/>
  </ItemGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
  </ItemGroup>
</Project>
