<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp"/>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all"/>
    <FrameworkReference Include="Microsoft.AspNetCore.App"/>
    <ProjectReference Include="../../src/Portia.DependencyInjection/Portia.DependencyInjection.csproj"/>
    <ProjectReference Include="../../src/Portia.AspNetCore/Portia.AspNetCore.csproj"/>
    <ProjectReference Include="../../src/Portia.Generators/Portia.Generators.csproj"/>
    <ProjectReference Include="../../src/Portia.AspNetCore.Generators/Portia.AspNetCore.Generators.csproj"/>
  </ItemGroup>
</Project>
