<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Testing utilities for Portia: an in-memory event store, and fake permission/actor-validator implementations.</Description>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Portia.Abstractions/Portia.Abstractions.csproj" />
  </ItemGroup>
</Project>
