<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>Portia analyzers, source generators, and code fixes for Portia applications.</Description>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Remove="Microsoft.CodeAnalysis.PublicApiAnalyzers"/>
    <AdditionalFiles Remove="$(MSBuildProjectDirectory)/PublicAPI.Shipped.txt"/>
    <AdditionalFiles Remove="$(MSBuildProjectDirectory)/PublicAPI.Unshipped.txt"/>
    <ProjectReference Include="../Portia.CodeFixes/Portia.CodeFixes.csproj" ReferenceOutputAssembly="false" PrivateAssets="all"/>
    <ProjectReference Include="../Portia.Generators/Portia.Generators.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="../Portia.Generators/bin/$(Configuration)/netstandard2.0/Portia.Generators.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    <None Include="../Portia.CodeFixes/bin/$(Configuration)/netstandard2.0/Portia.CodeFixes.dll" Pack="true" PackagePath="analyzers/dotnet/cs" Visible="false"/>
    <None Include="buildTransitive/Cntryl.Portia.Analyzers.props" Pack="true" PackagePath="buildTransitive/Cntryl.Portia.Analyzers.props" Visible="false"/>
  </ItemGroup>
</Project>
