<Project>
  <Import Project="../Directory.Build.props"/>

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Authors>cntryl</Authors>
    <RepositoryUrl>https://github.com/cntryl/portia</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../artifacts/packages</PackageOutputPath>
    <IsAotCompatible Condition="'$(MSBuildProjectName)' != 'Portia.Generators' and '$(MSBuildProjectName)' != 'Portia.Analyzers' and '$(MSBuildProjectName)' != 'Portia.CodeFixes'">true</IsAotCompatible>
    <WarningsAsErrors>$(WarningsAsErrors);CS1591</WarningsAsErrors>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)../README.md" Pack="true" PackagePath="/"/>
  </ItemGroup>
</Project>
