<Project>
  <Import Project="../Directory.Build.props" />

  <PropertyGroup>
    <IsPackable>true</IsPackable>
    <Authors>cntryl</Authors>
    <RepositoryUrl>https://github.com/cntryl/portia</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <PackageOutputPath>$(MSBuildThisFileDirectory)../artifacts/packages</PackageOutputPath>
  </PropertyGroup>
</Project>
